// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64      `json:"id"`
	UserID     string     `json:"user_id"`
	KeyHash    string     `json:"key_hash"`
	KeyPrefix  string     `json:"key_prefix"`
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	UsageCount int64      `json:"usage_count"`
}

type ClickEvent struct {
	Time            time.Time   `json:"time"`
	EventID         pgtype.UUID `json:"event_id"`
	UrlID           int64       `json:"url_id"`
	Referrer        *string     `json:"referrer"`
	UserAgent       string      `json:"user_agent"`
	IpAddress       netip.Addr  `json:"ip_address"`
	CountryCode     *string     `json:"country_code"`
	CountryName     *string     `json:"country_name"`
	City            *string     `json:"city"`
	Latitude        *float64    `json:"latitude"`
	Longitude       *float64    `json:"longitude"`
	DeviceType      string      `json:"device_type"`
	Browser         *string     `json:"browser"`
	OperatingSystem *string     `json:"operating_system"`
}

type ClickSummaryDaily struct {
	Day            interface{} `json:"day"`
	UrlID          int64       `json:"url_id"`
	TotalClicks    int64       `json:"total_clicks"`
	UniqueVisitors int64       `json:"unique_visitors"`
	MobileClicks   int64       `json:"mobile_clicks"`
	DesktopClicks  int64       `json:"desktop_clicks"`
}

type ClickSummaryHourly struct {
	Hour           interface{} `json:"hour"`
	UrlID          int64       `json:"url_id"`
	TotalClicks    int64       `json:"total_clicks"`
	UniqueVisitors int64       `json:"unique_visitors"`
	MobileClicks   int64       `json:"mobile_clicks"`
	DesktopClicks  int64       `json:"desktop_clicks"`
	TabletClicks   int64       `json:"tablet_clicks"`
	BotClicks      int64       `json:"bot_clicks"`
}

type Url struct {
	SnowflakeID    int64      `json:"snowflake_id"`
	ShortCode      string     `json:"short_code"`
	DestinationUrl string     `json:"destination_url"`
	Title          string     `json:"title"`
	Notes          *string    `json:"notes"`
	Status         string     `json:"status"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	ExpiresAt      *time.Time `json:"expires_at"`
	CreatorUserID  string     `json:"creator_user_id"`
	TotalClicks    int64      `json:"total_clicks"`
	LastClickedAt  *time.Time `json:"last_clicked_at"`
}

type User struct {
	ZitadelSub string    `json:"zitadel_sub"`
	Email      string    `json:"email"`
	CreatedAt  time.Time `json:"created_at"`
	LastSyncAt time.Time `json:"last_sync_at"`
	Status     string    `json:"status"`
}
