// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package db

import (
	"context"
	"time"
)

const createURL = `-- name: CreateURL :one
INSERT InTO urls (
    snowflake_id,
    short_code,
    destination_url,
    title,
    notes,
    status,
    created_at,
    updated_at,
    expires_at,
    creator_user_id,
    total_clicks,
    last_clicked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING snowflake_id, short_code, destination_url, title, notes, status, created_at, updated_at, expires_at, creator_user_id, total_clicks, last_clicked_at
`

type CreateURLParams struct {
	SnowflakeID    int64      `json:"snowflake_id"`
	ShortCode      string     `json:"short_code"`
	DestinationUrl string     `json:"destination_url"`
	Title          string     `json:"title"`
	Notes          *string    `json:"notes"`
	Status         string     `json:"status"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	ExpiresAt      *time.Time `json:"expires_at"`
	CreatorUserID  string     `json:"creator_user_id"`
	TotalClicks    int64      `json:"total_clicks"`
	LastClickedAt  *time.Time `json:"last_clicked_at"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.SnowflakeID,
		arg.ShortCode,
		arg.DestinationUrl,
		arg.Title,
		arg.Notes,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.CreatorUserID,
		arg.TotalClicks,
		arg.LastClickedAt,
	)
	var i Url
	err := row.Scan(
		&i.SnowflakeID,
		&i.ShortCode,
		&i.DestinationUrl,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CreatorUserID,
		&i.TotalClicks,
		&i.LastClickedAt,
	)
	return i, err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT snowflake_id, short_code, destination_url, title, notes, status, created_at, updated_at, expires_at, creator_user_id, total_clicks, last_clicked_at FROM urls
WHERE short_code = $1
LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.SnowflakeID,
		&i.ShortCode,
		&i.DestinationUrl,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CreatorUserID,
		&i.TotalClicks,
		&i.LastClickedAt,
	)
	return i, err
}
