// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: safebrowsing.proto

package sbproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchHashesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullHashes    []*FullHash            `protobuf:"bytes,1,rep,name=full_hashes,json=fullHashes,proto3" json:"full_hashes,omitempty"`
	CacheDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=cache_duration,json=cacheDuration,proto3" json:"cache_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHashesResponse) Reset() {
	*x = SearchHashesResponse{}
	mi := &file_safebrowsing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHashesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHashesResponse) ProtoMessage() {}

func (x *SearchHashesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHashesResponse.ProtoReflect.Descriptor instead.
func (*SearchHashesResponse) Descriptor() ([]byte, []int) {
	return file_safebrowsing_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHashesResponse) GetFullHashes() []*FullHash {
	if x != nil {
		return x.FullHashes
	}
	return nil
}

func (x *SearchHashesResponse) GetCacheDuration() *durationpb.Duration {
	if x != nil {
		return x.CacheDuration
	}
	return nil
}

type FullHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullHash      []byte                 `protobuf:"bytes,1,opt,name=full_hash,json=fullHash,proto3" json:"full_hash,omitempty"`
	Attributes    []string               `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullHash) Reset() {
	*x = FullHash{}
	mi := &file_safebrowsing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullHash) ProtoMessage() {}

func (x *FullHash) ProtoReflect() protoreflect.Message {
	mi := &file_safebrowsing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullHash.ProtoReflect.Descriptor instead.
func (*FullHash) Descriptor() ([]byte, []int) {
	return file_safebrowsing_proto_rawDescGZIP(), []int{1}
}

func (x *FullHash) GetFullHash() []byte {
	if x != nil {
		return x.FullHash
	}
	return nil
}

func (x *FullHash) GetAttributes() []string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_safebrowsing_proto protoreflect.FileDescriptor

const file_safebrowsing_proto_rawDesc = "" +
	"\n" +
	"\x12safebrowsing.proto\x12\fsafebrowsing\x1a\x1egoogle/protobuf/duration.proto\"\x91\x01\n" +
	"\x14SearchHashesResponse\x127\n" +
	"\vfull_hashes\x18\x01 \x03(\v2\x16.safebrowsing.FullHashR\n" +
	"fullHashes\x12@\n" +
	"\x0ecache_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rcacheDuration\"G\n" +
	"\bFullHash\x12\x1b\n" +
	"\tfull_hash\x18\x01 \x01(\fR\bfullHash\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x03(\tR\n" +
	"attributesB\vZ\t./sbprotob\x06proto3"

var (
	file_safebrowsing_proto_rawDescOnce sync.Once
	file_safebrowsing_proto_rawDescData []byte
)

func file_safebrowsing_proto_rawDescGZIP() []byte {
	file_safebrowsing_proto_rawDescOnce.Do(func() {
		file_safebrowsing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_safebrowsing_proto_rawDesc), len(file_safebrowsing_proto_rawDesc)))
	})
	return file_safebrowsing_proto_rawDescData
}

var file_safebrowsing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_safebrowsing_proto_goTypes = []any{
	(*SearchHashesResponse)(nil), // 0: safebrowsing.SearchHashesResponse
	(*FullHash)(nil),             // 1: safebrowsing.FullHash
	(*durationpb.Duration)(nil),  // 2: google.protobuf.Duration
}
var file_safebrowsing_proto_depIdxs = []int32{
	1, // 0: safebrowsing.SearchHashesResponse.full_hashes:type_name -> safebrowsing.FullHash
	2, // 1: safebrowsing.SearchHashesResponse.cache_duration:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_safebrowsing_proto_init() }
func file_safebrowsing_proto_init() {
	if File_safebrowsing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_safebrowsing_proto_rawDesc), len(file_safebrowsing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_safebrowsing_proto_goTypes,
		DependencyIndexes: file_safebrowsing_proto_depIdxs,
		MessageInfos:      file_safebrowsing_proto_msgTypes,
	}.Build()
	File_safebrowsing_proto = out.File
	file_safebrowsing_proto_goTypes = nil
	file_safebrowsing_proto_depIdxs = nil
}
