-- +goose Up
-- +goose StatementBegin
-- Remove auto-increment from id column
ALTER TABLE urls ALTER COLUMN id DROP DEFAULT;

-- Drop the sequence (no longer needed with Snowflake IDs)
DROP SEQUENCE IF EXISTS urls_id_seq;

-- Add comment explaining Snowflake IDs
COMMENT ON COLUMN urls.id IS 'Snowflake ID (generated by application layer)';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- Recreate the sequence
CREATE SEQUENCE urls_id_seq;

-- Restore auto-increment to id column
ALTER TABLE urls ALTER COLUMN id SET DEFAULT nextval('urls_id_seq');

-- Set sequence to max ID + 1
SELECT setval('urls_id_seq', COALESCE((SELECT MAX(id) FROM urls), 0) + 1, false);

-- Remove comment
COMMENT ON COLUMN urls.id IS NULL;
-- +goose StatementEnd
