// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ListURLs(ctx context.Context, userID string) ([]Url, error)
}

var _ Querier = (*Queries)(nil)
