// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"
	"time"
)

const countActiveURLsByUser = `-- name: CountActiveURLsByUser :one
SELECT COUNT(*)
FROM urls
WHERE user_id = $1
AND status = 'active'
`

func (q *Queries) CountActiveURLsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveURLsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countURLsByUser = `-- name: CountURLsByUser :one
SELECT COUNT(*)
FROM urls
WHERE user_id = $1
`

func (q *Queries) CountURLsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countURLsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (id, short_code, original_url, title, user_id, expires_at) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, short_code, original_url, user_id, created_at, updated_at, expires_at, status, title
`

type CreateURLParams struct {
	ID          int64      `json:"id"`
	ShortCode   string     `json:"short_code"`
	OriginalUrl string     `json:"original_url"`
	Title       string     `json:"title"`
	UserID      string     `json:"user_id"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.ID,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.Title,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Title,
	)
	return i, err
}

const getActiveURLByShortCode = `-- name: GetActiveURLByShortCode :one
SELECT  id, short_code, original_url, user_id, created_at, updated_at, expires_at, status, title
FROM urls
WHERE short_code = $1
AND status = 'active'
`

func (q *Queries) GetActiveURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getActiveURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Title,
	)
	return i, err
}

const listURLs = `-- name: ListURLs :many
SELECT  id, short_code, original_url, user_id, created_at, updated_at, expires_at, status, title
FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListURLs(ctx context.Context, userID string) ([]Url, error) {
	rows, err := q.db.Query(ctx, listURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
