// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"
)

const listURLs = `-- name: ListURLs :many
SELECT id, short_code, original_url, user_id, created_at, updated_at, expires_at, status FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListURLs(ctx context.Context, userID string) ([]Url, error) {
	rows, err := q.db.Query(ctx, listURLs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
