/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedurlsDashboardRouteImport } from './routes/_authenticated/(urls)/dashboard'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth/auth/callback'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedurlsDashboardRoute =
  AuthenticatedurlsDashboardRouteImport.update({
    id: '/(urls)/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/_auth/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/test': typeof AuthenticatedTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/dashboard': typeof AuthenticatedurlsDashboardRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/test': typeof AuthenticatedTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/dashboard': typeof AuthenticatedurlsDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/_authenticated/(urls)/dashboard': typeof AuthenticatedurlsDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/test' | '/' | '/auth/callback' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/test' | '/' | '/auth/callback' | '/dashboard'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/test'
    | '/_authenticated/'
    | '/_auth/auth/callback'
    | '/_authenticated/(urls)/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(urls)/dashboard': {
      id: '/_authenticated/(urls)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedurlsDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedurlsDashboardRoute: typeof AuthenticatedurlsDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedurlsDashboardRoute: AuthenticatedurlsDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
