/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization/$organizationView'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as ProtectedmainIndexRouteImport } from './routes/_protected/(main)/index'
import { Route as OrganizationSlugOrganizationViewRouteImport } from './routes/organization/$slug/$organizationView'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAccountAccountViewRouteImport } from './routes/_protected/account/$accountView'
import { Route as ProtectedmainUrlsRouteImport } from './routes/_protected/(main)/urls'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedmainIndexRoute = ProtectedmainIndexRouteImport.update({
  id: '/(main)/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const OrganizationSlugOrganizationViewRoute =
  OrganizationSlugOrganizationViewRouteImport.update({
    id: '/organization/$slug/$organizationView',
    path: '/organization/$slug/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountAccountViewRoute =
  ProtectedAccountAccountViewRouteImport.update({
    id: '/account/$accountView',
    path: '/account/$accountView',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedmainUrlsRoute = ProtectedmainUrlsRouteImport.update({
  id: '/(main)/urls',
  path: '/urls',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedmainIndexRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/urls': typeof ProtectedmainUrlsRoute
  '/account/$accountView': typeof ProtectedAccountAccountViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization/$slug/$organizationView': typeof OrganizationSlugOrganizationViewRoute
}
export interface FileRoutesByTo {
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/urls': typeof ProtectedmainUrlsRoute
  '/account/$accountView': typeof ProtectedAccountAccountViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization/$slug/$organizationView': typeof OrganizationSlugOrganizationViewRoute
  '/': typeof ProtectedmainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth/$authView': typeof AuthAuthViewRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/_protected/(main)/urls': typeof ProtectedmainUrlsRoute
  '/_protected/account/$accountView': typeof ProtectedAccountAccountViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization/$slug/$organizationView': typeof OrganizationSlugOrganizationViewRoute
  '/_protected/(main)/': typeof ProtectedmainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$authView'
    | '/organization/$organizationView'
    | '/urls'
    | '/account/$accountView'
    | '/api/auth/$'
    | '/organization/$slug/$organizationView'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/$authView'
    | '/organization/$organizationView'
    | '/urls'
    | '/account/$accountView'
    | '/api/auth/$'
    | '/organization/$slug/$organizationView'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/auth/$authView'
    | '/organization/$organizationView'
    | '/_protected/(main)/urls'
    | '/_protected/account/$accountView'
    | '/api/auth/$'
    | '/organization/$slug/$organizationView'
    | '/_protected/(main)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OrganizationSlugOrganizationViewRoute: typeof OrganizationSlugOrganizationViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/(main)/': {
      id: '/_protected/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedmainIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/organization/$slug/$organizationView': {
      id: '/organization/$slug/$organizationView'
      path: '/organization/$slug/$organizationView'
      fullPath: '/organization/$slug/$organizationView'
      preLoaderRoute: typeof OrganizationSlugOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account/$accountView': {
      id: '/_protected/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof ProtectedAccountAccountViewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(main)/urls': {
      id: '/_protected/(main)/urls'
      path: '/urls'
      fullPath: '/urls'
      preLoaderRoute: typeof ProtectedmainUrlsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedmainUrlsRoute: typeof ProtectedmainUrlsRoute
  ProtectedAccountAccountViewRoute: typeof ProtectedAccountAccountViewRoute
  ProtectedmainIndexRoute: typeof ProtectedmainIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedmainUrlsRoute: ProtectedmainUrlsRoute,
  ProtectedAccountAccountViewRoute: ProtectedAccountAccountViewRoute,
  ProtectedmainIndexRoute: ProtectedmainIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthAuthViewRoute: AuthAuthViewRoute,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OrganizationSlugOrganizationViewRoute: OrganizationSlugOrganizationViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
