FROM golang:1 AS base
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download

FROM base AS build-redirector
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/redirector/main.go

FROM scratch AS redirector
WORKDIR /app
COPY --from=build-redirector /app/main .
CMD ["./main"]
