FROM golang:1 AS base
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download

FROM base AS build-api
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/api/main.go

FROM scratch AS api
WORKDIR /app
COPY --from=build-api /app/main .
CMD ["./main"]