FROM golang:1 AS api

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD [ "air", "--build.cmd", "go build -o ./tmp/main ./cmd/api/main.go", "--build.entrypoint", "./tmp/main", "--build.poll", "true" ]

FROM golang:1 AS redirector

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD [ "air", "--build.cmd", "go build -o ./tmp/main ./cmd/redirector/main.go", "--build.entrypoint", "./tmp/main", "--build.poll", "true" ]